[frontend]
100.53.219.106

[mongodb]
mongodb.anjana.fun

[redis]
redis.anjana.fun

[mysql]
mysql.anjana.fun

[rabbitmq]
rabbitmq.anjana.fun

[catalouge]
catalouge.anjana.fun

[cart]
cart.anjana.fun

[user]
user.anjana.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[localServer]
localhost

[localServer:vars] #inventory variables defined via groupname:vars here two groups rontend n local server
NAME=from inventory
FAVCOLOUR=Peach
NAME= Anjana
CITY= Delhi